@host = http://localhost

GET {{host}}:{{$dotenv PORT}}/ HTTP/1.1
Content-Type: application/json


###

POST {{host}}:{{$dotenv PORT}}/links HTTP/1.1
Content-Type: application/json

{
  "fullUrl": "https://github.com/dienerld",
  "shortUrl": "dienerld1",
  "expiresAt":"2022-01-17T22:37:07.079Z"
}


###
GET {{host}}:{{$dotenv PORT}}/dienerld1 HTTP/1.1


###
GET {{host}}:{{$dotenv PORT}}/dienerld1/stats HTTP/1.1
